<?php
/**
 * Created by PhpStorm.
 * User: Prabhash
 * Date: 6/30/2020
 * Time: 10:48 AM
 */

class PricingPage extends Page
{
    public function getControllerName(){
        return PricingPageController::class;

    }

    private static $has_many = [
        'PricingPlans' => PricingPlan::class,
    ];

    public function getCMSFields()
    {
        $fields =  parent::getCMSFields();
        $conf = \SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor::create();
        $fields->addFieldsToTab('Root.Main', [
            \SilverStripe\Forms\GridField\GridField::create('PricingPlans', 'PricingPlans', $this->PricingPlans(), $conf)
        ]);
        return $fields;
        // TODO: Change the autogenerated stub
    }

    public function PaymentLink(){
         if($page = PaymentPage::get()->first()){
             return $page->Link();
        }
    }



}
