<?php
/**
 * Created by PhpStorm.
 * User: Prabhash
 * Date: 10/30/2020
 * Time: 1:36 PM
 */
use SilverStripe\ORM\DataObject;
use SilverStripe\Assets\Image;
use SilverStripe\AssetAdmin\Forms\UploadField;
use SilverStripe\Forms\TextField;

class TeamMember extends DataObject
{
    private static $db = [

        'Name' => 'Varchar',
        'JobTitle' => 'Varchar',
        'FbLink' => 'Varchar',
        'TwitterLink' => 'Varchar',
        'InstaLink' => 'Varchar',
        'LinkedIn' => 'Varchar',
    ];

    private static $has_one = [
        'ProfilePhoto' => Image::class,
        'AboutUs' => AboutUsPage::class,
    ];

    private static $owns = [
        'ProfilePhoto'

    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->removeByName('AboutUsID');
        $fields->addFieldsToTab('Root.Main', [
           UploadField::create('ProfilePhoto'),
            TextField::create('Name'),
            TextField::create('JobTitle'),
            TextField::create('TwitterLink'),
            TextField::create('InstaLink'),
            TextField::create('LinkedIn'),
        ]);
        return $fields;
        // TODO: Change the autogenerated stub
    }
}
