<?php
/**
 * Created by PhpStorm.
 * User: Prabhash
 * Date: 10/30/2020
 * Time: 1:36 PM
 */
use SilverStripe\ORM\DataObject;
use SilverStripe\Assets\Image;
use SilverStripe\AssetAdmin\Forms\UploadField;
use SilverStripe\Forms\TextField;
use SilverStripe\Forms\HTMLEditor\HTMLEditorField;

class UserExperience extends DataObject
{
    private static $db = [

        'CustomerName' => 'Varchar',
        'Position' => 'Varchar',
        'Comment' => 'HTMLText',

    ];

    private static $has_one = [
        'CustomerPhoto' => Image::class,
        'AboutUs' => AboutUsPage::class,
    ];

    private static $owns = [
        'CustomerPhoto'

    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->removeByName('AboutUsID');
        $fields->addFieldsToTab('Root.Main', [
            UploadField::create('CustomerPhoto'),
            TextField::create('CustomerName'),
            TextField::create('Position'),
            HTMLEditorField::create('Comment'),


        ]);
        return $fields;
        // TODO: Change the autogenerated stub
    }
}
